log:
  file: casserver.log
  level: DEBUG
  
db_log:
  file: casserver_db.log

authenticator: CASServer::Authenticators::ActiveDirectoryLDAP

ldap:
  server: ad.example.com
  port: 389
  base: dc=example,dc=com
  filter: (objectClass=person)
  auth_user: authenticator
  auth_password: 1234example